Browser support page added Turkish language
ToplulukTR/preact-www pull request #2
Opened 2018-03-06 05:23 UTC by irfansener

2018-03-06 08:33 UTC, mehmetkose commented on content/lang/tr/about/browser-support.md
> -Preact supports modern browsers (Chrome, Firefox, Safari, Edge) and IE9+. It should work fine in IE7 and IE8, but requires some polyfills. If you intend to use it and support those older browsers, it
Belki polyfill'i olduğu gibi kullanmak daha anlamlı olabilir

2018-03-06 20:10 UTC, dbyilmaz commented on content/lang/tr/about/demos-examples.md
> +> :information_desk_person: _Sizinde mi bir örneğiniz var ?
_Sizinde mi bir örneğiniz var?_

2018-03-06 20:12 UTC, dbyilmaz commented on content/lang/tr/about/demos-examples.md
> +Tabii ki de bu site Preact ile geliştirildi.
Tabi ki de

2018-03-06 21:47 UTC, irfansener commented on content/lang/tr/about/browser-support.md
> -Preact supports modern browsers (Chrome, Firefox, Safari, Edge) and IE9+. It should work fine in IE7 and IE8, but requires some polyfills. If you intend to use it and support those older browsers, it
"Bazı polyfilller kullanmanız gerekir." gibi bir cümle bana  epey itici geliyor. Eklenti yerine paket olarak değiştirdim. Başka önerin var mı ?

2018-03-06 22:31 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +> :information_desk_person: _Sizinde mi bir örneğiniz var ?
@dbyilmaz  Sizin de mi bir örneğiniz var?

2018-03-06 22:36 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +Preact + Redux örnek projesi, basit bir to-do list uygulaması.
@irfansener burda uygulaması değil uygunlanması demek istemiş. 
"Preact + Redux örnek projesi, basit bir to-do list'e uygulanması."
daha doğru bir kullanım

2018-03-06 22:46 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +Minimal Preact yapısı ile ihtiyaç duyulan tüm araçlar dahil edilmiş, yeni projeye başlamanın en doğru yolu.
Minimal Preact yapısı ile projenizi hemen başlatmak için gerekli tüm araçlar.

2018-03-06 22:50 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +Yıldırım hızında bir başlangıç kiti. Küçük/Orta ölçekli proje yapıları için ideal.
Yıldırım hızında prototipleme ve küçük/orta ölçükli proje yapısı için başlangıç paketi.

2018-03-06 22:51 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +- [Animasyonlu yazı](http://codepen.io/developit/full/LpNOdm/) _(@ CodePen)_
Animasyonlu Metin

2018-03-06 22:59 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +Doğal dil işleme tabanlı bir web vr oluşturucusu.
Doğal dil tabanlı Web VR hikaye yaratıcısı.

2018-03-06 23:08 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +Chrome Dev Summit 2016'dan katılımcılara  Progressive Web App sunumu!
Chrome Dev Summit 2016'dan kitle katılımı Progressive Web uygulaması.

2018-03-06 23:10 UTC, gokhanamal commented on content/lang/tr/about/demos-examples.md
> +Preact, Electron ve Photon ile oluşturulmuş Dropbox için masaüstü uygulaması.
Dropbox için Preact, Electron ve Photon ile oluşturulmuş masaüstü uygulaması.

2018-03-08 06:15 UTC, SelmanKahya requested changes

2018-03-08 06:15 UTC, SelmanKahya commented on content/lang/tr/about/browser-support.md
> +Preact modern tüm tarayıcıları destekler (Chrome, Firefox, Safari, Edge) ve IE9+. Fakat Internet Explorer 7 ve 8 sürümlerinde düzgün çalışmayabilir. Eğer I7 ve I8 gibi eski tarayıcılar için destek ve
Preact modern tüm tarayıcıları destekler (Chrome, Firefox, Safari, Edge) ve IE9+.
yerine
Preact modern tüm tarayıcıları (Chrome, Firefox, Safari, Edge) ve IE9 üstünü destekler.

Eğer I7 ve I8 gibi eski tarayıcılar için destek vermek isterseniz, bazı paketleri kullanmanız gerekmektedir.
yerine
Eğer IE7 ve IE8 gibi eski tarayıcıları kullanmak ve desteklenmek isterseniz, bazı paketleri kullanmanız gerekmektedir.

2018-03-08 06:15 UTC, SelmanKahya commented on content/lang/tr/about/demos-examples.md
> +Bu sayfada Preact öğrenmek için kullanabileceğiniz demolar ve örnekler listelenmiştir
en sona nokta

2018-03-08 06:15 UTC, SelmanKahya commented on content/lang/tr/about/demos-examples.md
> +Preact & Material Design Lite kullanarak geliştirilmiş.
geliştirilmiş -- geliştirildi

2018-03-08 06:15 UTC, SelmanKahya commented on content/lang/tr/about/demos-examples.md
> +Chrome Dev Summit 2016'dan katılımcılara  Progressive Web App sunumu!
katılımcılara  Progressive arasında iki boşluk var

2018-03-08 06:15 UTC, SelmanKahya commented on content/lang/tr/about/demos-examples.md
>  - [60FPS Rainbow Spiral](http://codepen.io/developit/full/xGoagz/) _(@ CodePen)_
Gökkuşağı spirali

2018-03-08 06:15 UTC, SelmanKahya commented on content/lang/tr/about/demos-examples.md
> +TodoMVC için çevrimdışı senkronizasyon PuchDB ile birlikte [PouchDB](https://pouchdb.com/).
Çevrimdışı senkronizasyon destekli TodoMVC ([PouchDB](https://pouchdb.com/) ile).

2018-03-08 17:24 UTC, irfansener reviewed
All reviews has been applied.

2018-03-10 10:09 UTC, merged