switching-to-preact cevirisini ekle
ToplulukTR/preact-www pull request #3
Opened 2018-03-06 11:39 UTC by hiimnew

2018-03-06 16:27 UTC, gokhanamal commented on content/lang/tr/guide/switching-to-preact.md
> +Bu dependency leri yükledikten sonra, build konfigürasyonunuzu React import dosyalarına alias olacak şekilde yapmalısınız ki Preact'a işaret edebilsin.
"dependency leri" yerine "bu gereksinimleri" daha mantıklı olmaz mı? Başka bir türkçe kelime de bulabilir

2018-03-06 18:38 UTC, hiimnew commented on content/lang/tr/guide/switching-to-preact.md
> +Bu dependency leri yükledikten sonra, build konfigürasyonunuzu React import dosyalarına alias olacak şekilde yapmalısınız ki Preact'a işaret edebilsin.
Evet yazarken tereddüt ettim ben de, ama dependency biraz kalıplaşmış gibi package.json da falan da var, o yüzden Türkçe bir kelime kullanırsam şimdi başka bir şey anlaşılır diye tekrar dependecy olarak bıraktım.

2018-03-06 20:14 UTC, dbyilmaz commented on content/lang/tr/guide/switching-to-preact.md
> +Bu dependency leri yükledikten sonra, build konfigürasyonunuzu React import dosyalarına alias olacak şekilde yapmalısınız ki Preact'a işaret edebilsin.
@hiimnew  gereksinim demek daha mantıklı.

2018-03-08 06:42 UTC, SelmanKahya requested changes

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +1. `preact-compat` alias ı yüklemek
alias'ını yüklemek

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +2. import ettiğiniz dosyaları `preact` a çevirmek ve uyumsuz kodları silmek
import `react` kodunu `preact` a çevirmek ve uyumsuz kodları silmek

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +`preact-compat` projenizde yaklaşık olarak 2 kb yük getirirken aynı zamanda ihtiyacınız olan tüm desteği sağlar.
`preact-compat` projenizde yaklaşık olarak 2 kb yük getirirken aynı zamanda npm üzerinden bulabileceğiniz birçok React modülünü kullanabilmenizi sağlar.

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Tek bir modülün içerisinde Preact'ı `react` ve `react-dom` gibi çalışmasına yetecek şekilde ihtiyacınız olan tüm ayarlar...
The `preact-compat` package provides all the necessary tweaks on top of Preact's core to make it work just like `react` and `react-dom`, in a single module.

`preact-compat` paketi, Preact'in çekirdeğinin tek bir modülde `react` and `react-dom` gibi çalışmasını sağlayacak değişiklikleri sağlar.

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +
fazladan yeni satır

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Öncelikle preact ve preact-compat i indirmelisiniz (ikisi farklı paketlerdir.):
preact-compat'i

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Öncelikle preact ve preact-compat i indirmelisiniz (ikisi farklı paketlerdir.):
farklı paketlerdir.) -- farklı paketlerdir)

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +### preact-compat' için Alias Oluşturmak
fazladan tırnak '

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Şimdi dependency dosyalarınız yüklendiğine göre, build sistem konfigürasyonunuzu `react` ve ya `react-dom` import eden ve çalışması için gereken tüm dosyaları `preact-compat` a yönlendirmelisiniz.
Şimdi gereken kütüphaneler/gereksinimler yüklendiğine göre,

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Eğer bir build sistemi kullanmıyorsanız ve ya kalıcı olarak `preact-compat` e geçmek istiyorsanız, Projenizdeki tüm import ve require ları bulup değiştirerek aliasın üstenlendiği görevi kendiniz de g
```
veya
`preact-compat`'e
Projenizdeki -- projenizdeki
require'ları
alias'ın
kendiniz de yapabilirsiniz
```

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +>**bul:** `(['"])react(-dom)?\1`
boşluk gitmiş

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +>**yerine-koy** `$1preact-compat$1`
boşluk gitmiş

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Bu durumda, direkt olarak `preact` a geçmek, `preact-compat` e bağlı geçişten daha zorlayıcı olabilir.
```
`preact`'a
compat`'e
```

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Preact'ın özü oldukça özelliklerle doludur, ve pek çok React ile özdeşleşmiş kodlar direkt olarak `preact` a az bir uğraş ile geçirilebilir.
+Preact'ın core kısmı olukça gelişmiştir ve pek çok React projesi az bir uğraşla `preact`'a geçirilebilir.

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +#### module-alias Kullanarak Node içerisinde Alias Oluşturmak
Module-alias kullanarak Node içerisinde Alias oluşturmak

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +SSR gereksinimlerince, Eğer sunucu taraflı projenizde webpack gibi bir bundler kullanmıyorsanız, [module-alias](https://www.npmjs.com/package/module-alias) kullanarak react'ı preact ile değiştirebili
```
SSR için, eğer sunucu taraflı projenizde webpack gibi bir bundler kullanmıyorsanız, [module-alias](https://www.npmjs.com/package/module-alias) kullanarak react'ı preact ile değiştirebilirsiniz.
```

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Eğer sunucunuzda yeni `import` söz dizimini Babel ile kullanıyorsanız, bu satırları diğer import ettiklerinizin üstüne koymak işe yaramayacaktır, çünkü Babel tüm import edilen dosyaları modülün en te
```
Eğer sunucunuzda -- Eğer sunucu tarafında
import edin(`import -- import edin (`import  (parantezden once boşluk ekledim)
```

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +`module-alias` kullanmadan da node içerisinde alias oluşturmak mümkün. Bu Node'un modül sisteminin özelliklerinin üzerine kuruludur, o yüzden dikkatli olmanız gerekir. Manüel olarak alias oluşturmak.
en sonda iki nokta olmalı

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +**İşler tamam!**
İşlem tamam nasıl olur?

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +## En ideali: Preacta Geçiş
Preact'a

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +React'tan Preact'a geçmek için `preact-compat` i projenizde kullanmak zorunda değilsiniz.
```
`preact-compat`'i
```

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Preact'ın API'ı neredeyse React'ınki ile aynıdır, ve birçok React kodları ya ufak değişikliler ile ya da ona bile gerek kalmadan geçiş yapabilir.
kalmadan geçiş yapabilir. -- kalmadan geçirilebilir.

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +### 2. JSX Pragması: `h()` e transpile etmek
e den önce tırnak

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +> **Hikayenin tamamı:** JSX dil uzantısı React'tan bağımsız olsa da, [Babel] ve [Bublé] gibi popüler transpilerlar `React.createElement()` fonksiyonunu çağırmayı varsayar.
transpiler'lar
 fonksiyonunu otomatik olarak çağırmaya çalışır

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +> Bunun tarihsel nedenleri vardır, ama JSX fonksiyonları aslında önceden var olan bir teknoloji olan [hyperscript] ile mümkündür.
mümkündür -- mümkün olmuştur

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +> ve bu teknolojiye atıfta bulunarak `h()` fonksiyonunu JSX pragması olarak kullanır.
kullanır -- kullanmayı hedefler

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +JSX te, "pragma" her bir elementi oluşturma işini üstlenen fonksiyonun adıdır.
JSX'te

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Eğer Babel kullanıyorsanız, JSX pragmasını `.babelrc` ve ya `package.json` dosylarıyla belirtebilirsiniz. (hangisini tercih ederseniz)
dosylarıyla -- dosyalarında

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +#### Açıklama Satırlarıyla
Yorum Satırlarıyla

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Eğer Babel'i baz alarak çalışan bir online editörde iseniz (JSFiddle ve ya Codepen gibi), JSX pragmasını aşağıdaki kod satırını dosyanızın ilk satırlarına koyarak belirtebilirsiniz.
ve ya -- veya

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Bunlardan en çok dikkat çeken `createClass()` fonksiyonudur. Nesne yönelimli programla ve sınıflar hakkında fikirler arası uçurum olsa da, anlamak gerekir ki JavaScript'te sınıflar virtual-dom kütüph
arası uçurum -- arasında uçurum

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +bu da komponentin yaşam döngüsündeki ince ayrıntılarda önemli rol oynar.
yeni satıra ihtiyaç var mı?

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Eğer hala String ref'leri kullanmak isterseniz, [bu küçük linkedRef fonksiyonu]() hala `this.refs.$$` kullanarak String Ref'ler gibi uzun ömürlü bir versiyon sunar.
() arasındaki link kaybolmuş

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Bu küçük kapsayıcının (wrapper) basitliği Function Ref ler aynı zamanda neden Function Ref lerin neden popüler olduğunu açıklamaktadır.
fazladan bir neden var

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +`render()` fonksiyonu `react-dom` tarafından sağlandığı biliniyor.
React 0.13 versiyonundan beri `render()` fonksiyonu `react-dom` tarafından sağlanıyor.

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +// yerel-güncelleme:
yerinde güncelleme

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +Bu çoğu durumda işe yarasa da (jsfiddles, codepens vb.), daha çok kontrollü olmakta fayda var.
daha kontrollü

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +`render()` fonksiyonunun neden kök (root) döndürdüğünü açıklar: 3. argümanı yerel güncelleme için kullanırsınız.
kökü

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
> +`render()` fonksiyonunun neden kök (root) döndürdüğünü açıklar: 3. argümanı yerel güncelleme için kullanırsınız.
3. argümanı yerinde güncelleme

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
>  // root holds our app's root DOM Element:
// kök uygulamanın kök DOM elemanını tutuyor:

2018-03-08 06:42 UTC, SelmanKahya commented on content/lang/tr/guide/switching-to-preact.md
>  if (module.hot) module.hot.accept('./app', init);
bir üst satırda, 
// örnek: Webpack HMR güncellemesinde re-render:

2018-04-27 14:44 UTC, merged